const MANIFEST_URL="data/manifest.json?v=20260512-4";
const GEO_URL="data/municipios.geojson?v=20260512-4";
const $=id=>document.getElementById(id);
const fmt=new Intl.NumberFormat("pt-BR");
const fmt1=new Intl.NumberFormat("pt-BR",{maximumFractionDigits:1});
let MANIFEST=[], DATA=[], GEO=null, MAP_UF=null, MAP_MUN=null, LAYER_UF=null, LAYER_MUN=null;
const CACHE={};

function parseCSV(text){const rows=[];let row=[],cell="",q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"'){q=!q}else if(c===","&&!q){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!q){if(c==="\r"&&n==="\n")i++;row.push(cell);if(row.some(v=>v.trim()!==""))rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const head=rows.shift().map(x=>x.trim());return rows.map(r=>{const o={};head.forEach((h,i)=>o[h]=(r[i]??"").trim());return o})}
function num(x){if(x===undefined||x===null||x==="")return null;const n=Number(String(x).replace(/\./g,"").replace(",","."));return Number.isFinite(n)?n:null}
function norm(r){const casos=num(r.casos)||0,pop=num(r.populacao);let inc=num(r.incidencia_100mil);if((inc===null||!Number.isFinite(inc))&&pop>0)inc=casos/pop*100000;return{doenca:(r.doenca||"").toUpperCase(),doenca_nome:r.doenca_nome||r.doenca,cod_mun6:String(r.cod_mun6||"").padStart(6,"0").slice(0,6),municipio:r.municipio||"",uf:(r.uf||"").toUpperCase(),ano:Number(r.ano),casos,populacao:pop,incidencia_100mil:inc}}
function group(rows,keys){const m=new Map();for(const r of rows){const k=keys.map(x=>r[x]).join("|");if(!m.has(k)){const o={casos:0,populacao:0,_pop:0,_muns:new Set(),_munsPos:new Set()};keys.forEach(x=>o[x]=r[x]);m.set(k,o)}const o=m.get(k);o.casos+=r.casos||0;if(Number.isFinite(r.populacao)){o.populacao+=r.populacao;o._pop++}if(r.cod_mun6)o._muns.add(r.cod_mun6);if(r.cod_mun6&&(r.casos||0)>0)o._munsPos.add(r.cod_mun6)}return[...m.values()].map(o=>{const pop=o._pop?o.populacao:null;const inc=pop?o.casos/pop*100000:null;const municipios=o._muns.size;const municipios_com_notificacao=o._munsPos.size;delete o._pop;delete o._muns;delete o._munsPos;return{...o,populacao:pop,incidencia_100mil:inc,municipios,municipios_com_notificacao}})}
async function loadDisease(code){if(CACHE[code]){DATA=CACHE[code];return}const item=MANIFEST.find(d=>d.codigo===code);if(!item)throw new Error("Doença não encontrada");$("row-count").textContent="carregando "+item.doenca+"...";const res=await fetch(item.arquivo+"?v=20260512-4");if(!res.ok)throw new Error("Arquivo da doença não encontrado: "+item.arquivo);DATA=parseCSV(await res.text()).map(norm).filter(r=>r.doenca&&r.cod_mun6&&Number.isFinite(r.ano));CACHE[code]=DATA;$("row-count").textContent=`${fmt.format(DATA.length)} linhas nesta doença | ${fmt.format(MANIFEST.reduce((a,b)=>a+b.linhas,0))} linhas no total`}
function setupDiseaseSelect(){MANIFEST.sort((a,b)=>a.doenca.localeCompare(b.doenca,"pt-BR"));$("disease").innerHTML=MANIFEST.map(d=>`<option value="${d.codigo}">${d.doenca}</option>`).join("")}
function setupFilters(){const oldYear=$("year").value,oldUf=$("uf").value;const years=[...new Set(DATA.map(r=>r.ano))].sort((a,b)=>a-b);$("year").innerHTML=years.map(y=>`<option>${y}</option>`).join("");$("year").value=years.includes(Number(oldYear))?oldYear:years.at(-1);const ufs=["",...[...new Set(DATA.map(r=>r.uf).filter(Boolean))].sort()];$("uf").innerHTML=ufs.map(u=>`<option value="${u}">${u||"Brasil"}</option>`).join("");if(ufs.includes(oldUf))$("uf").value=oldUf;updateMuns()}
function updateMuns(){const uf=$("uf").value;const muns=[...new Set(DATA.filter(r=>(!uf||r.uf===uf)).map(r=>r.municipio).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR"));$("mun-list").innerHTML=muns.map(m=>`<option value="${m}"></option>`).join("")}
function filtered(ignoreYear=false){const y=Number($("year").value),uf=$("uf").value,mun=$("mun").value.trim();return DATA.filter(r=>(ignoreYear||r.ano===y)&&(!uf||r.uf===uf)&&(!mun||r.municipio===mun))}
function getCode(f){const p=f.properties||{};const raw=p.cod_mun6||p.CD_MUN||p.CD_GEOCMU||p.GEOCODIGO||p.id||f.id||"";return String(raw).replace(/\D/g,"").padStart(7,"0").slice(0,6)}
const UF_BY_PREFIX={"11":"RO","12":"AC","13":"AM","14":"RR","15":"PA","16":"AP","17":"TO","21":"MA","22":"PI","23":"CE","24":"RN","25":"PB","26":"PE","27":"AL","28":"SE","29":"BA","31":"MG","32":"ES","33":"RJ","35":"SP","41":"PR","42":"SC","43":"RS","50":"MS","51":"MT","52":"GO","53":"DF"};
function color(v,max){if(!Number.isFinite(v)||v<=0||!Number.isFinite(max)||max<=0)return"#f1f5f9";const t=Math.min(1,v/max);if(t>.8)return"#7f1d1d";if(t>.6)return"#b91c1c";if(t>.4)return"#ef4444";if(t>.2)return"#f97316";return"#fed7aa"}
function initMaps(){if(!MAP_UF){MAP_UF=L.map("map-uf",{scrollWheelZoom:false}).setView([-14.2,-51.9],4);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap"}).addTo(MAP_UF)}if(!MAP_MUN){MAP_MUN=L.map("map-mun",{scrollWheelZoom:false}).setView([-14.2,-51.9],4);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap"}).addTo(MAP_MUN)}}
function renderMaps(rows){initMaps();if(!GEO){$("map-uf-status").textContent="GeoJSON municipal não encontrado";$("map-mun-status").textContent="GeoJSON municipal não encontrado";return}if(LAYER_UF){LAYER_UF.remove();LAYER_UF=null}if(LAYER_MUN){LAYER_MUN.remove();LAYER_MUN=null}const ind=$("indicator").value;const munRows=group(rows,["uf","cod_mun6","municipio"]);const byCode=new Map(munRows.map(r=>[r.cod_mun6,r]));const maxMun=Math.max(0,...munRows.map(r=>Number(r[ind]||0)));const ufRows=group(rows,["uf"]);const byUF=new Map(ufRows.map(r=>[r.uf,r]));const maxUF=Math.max(0,...ufRows.map(r=>Number(r[ind]||0)));
LAYER_UF=L.geoJSON(GEO,{style:f=>{const code=getCode(f),sigla=UF_BY_PREFIX[code.slice(0,2)]||"";const r=byUF.get(sigla);const v=r?r[ind]:0;return{color:"#94a3b8",weight:.25,fillColor:color(v,maxUF),fillOpacity:r&&v>0?.75:.05}},onEachFeature:(f,l)=>{const sigla=UF_BY_PREFIX[getCode(f).slice(0,2)]||"";const r=byUF.get(sigla);if(r)l.bindPopup(`<strong>${sigla}</strong><br>Casos: ${fmt.format(r.casos||0)}<br>Municípios com notificações: ${fmt.format(r.municipios_com_notificacao||0)}`)}}).addTo(MAP_UF);
LAYER_MUN=L.geoJSON(GEO,{style:f=>{const code=getCode(f);const r=byCode.get(code);const v=r?r[ind]:0;return{color:"#94a3b8",weight:.35,fillColor:color(v,maxMun),fillOpacity:r&&v>0?.78:.04}},onEachFeature:(f,l)=>{const code=getCode(f);const r=byCode.get(code);const name=(f.properties&&f.properties.name)||r?.municipio||code;if(r)l.bindPopup(`<strong>${name} - ${r.uf}</strong><br>Casos: ${fmt.format(r.casos||0)}<br>Incidência: ${Number.isFinite(r.incidencia_100mil)?fmt1.format(r.incidencia_100mil):"—"}`)}}).addTo(MAP_MUN);
try{MAP_UF.fitBounds(LAYER_UF.getBounds(),{padding:[15,15]});MAP_MUN.fitBounds(LAYER_MUN.getBounds(),{padding:[15,15]})}catch(e){}$("map-uf-status").textContent="Mapa por UF baseado na malha municipal";$("map-mun-status").textContent="Mapa municipal carregado"}
function refresh(){updateMuns();const rows=filtered(),total=group(rows,[])[0]||{casos:0,populacao:null,incidencia_100mil:null,municipios_com_notificacao:0};$("card-casos").textContent=fmt.format(total.casos||0);$("card-pop").textContent=total.populacao?fmt.format(total.populacao):"—";$("card-inc").textContent=Number.isFinite(total.incidencia_100mil)?fmt1.format(total.incidencia_100mil):"—";$("card-muns").textContent=fmt.format(total.municipios_com_notificacao||0);
const ser=group(filtered(true),["ano"]).sort((a,b)=>a.ano-b.ano);Plotly.newPlot("series",[{x:ser.map(r=>r.ano),y:ser.map(r=>r.casos),type:"bar",name:"Casos",marker:{color:"#1f77b4"}}],{margin:{t:20,r:20,b:45,l:60},yaxis:{title:"Casos/Ano"},xaxis:{title:"Ano"}},{responsive:true,displayModeBar:false});
const ind=$("indicator").value;const ufRank=group(DATA.filter(r=>r.ano===Number($("year").value)),["uf"]).filter(r=>r.uf&&(r[ind]||0)>0).sort((a,b)=>(b[ind]??-Infinity)-(a[ind]??-Infinity));Plotly.newPlot("ufs",[{x:ufRank.map(r=>r[ind]),y:ufRank.map(r=>r.uf),type:"bar",orientation:"h",marker:{color:ufRank.map((_,i)=>i<5?"#1e3a8a":"#60a5fa")},text:ufRank.map(r=>fmt.format(r[ind]||0)),textposition:"auto"}],{margin:{t:20,r:30,b:50,l:60},height:Math.max(420,ufRank.length*24),xaxis:{title:ind==="casos"?"Casos/Ano":"Incidência / 100 mil"},yaxis:{automargin:true,categoryorder:"total ascending"},plot_bgcolor:"#fff",paper_bgcolor:"#fff"},{responsive:true,displayModeBar:false});
const munRank=group(rows,["uf","cod_mun6","municipio"]).filter(r=>(r[ind]||0)>0).sort((a,b)=>(b[ind]??-Infinity)-(a[ind]??-Infinity)).slice(0,100);$("table").innerHTML="<thead><tr><th>UF</th><th>Código</th><th>Município</th><th>Casos/Ano</th><th>População/Ano</th><th>Incidência</th></tr></thead><tbody>"+munRank.map(r=>`<tr><td>${r.uf}</td><td>${r.cod_mun6}</td><td>${r.municipio}</td><td>${fmt.format(r.casos||0)}</td><td>${r.populacao?fmt.format(r.populacao):"—"}</td><td>${Number.isFinite(r.incidencia_100mil)?fmt1.format(r.incidencia_100mil):"—"}</td></tr>`).join("")+"</tbody>";renderMaps(rows)}
async function diseaseChanged(){await loadDisease($("disease").value);setupFilters();refresh()}
async function init(){const [manRes,geoRes]=await Promise.all([fetch(MANIFEST_URL),fetch(GEO_URL).catch(()=>null)]);if(!manRes.ok)throw new Error("Manifesto de dados não encontrado");MANIFEST=await manRes.json();if(geoRes&&geoRes.ok)GEO=await geoRes.json();setupDiseaseSelect();await diseaseChanged()}
$("apply").onclick=refresh;$("clear").onclick=()=>{$("uf").value="";$("mun").value="";refresh()};$("uf").onchange=()=>{$("mun").value="";refresh()};$("disease").onchange=diseaseChanged;$("year").onchange=refresh;$("indicator").onchange=refresh;init().catch(e=>alert("Erro: "+e.message));
